# Generated by Django 2.0.4 on 2018-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year_in_school',
            field=models.CharField(choices=[('BIKE', 'Bike'), ('CAR', 'Car')], default='BIKE', max_length=10),
        ),
    ]
