# Generated by Django 2.0.4 on 2018-08-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='year_in_school',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], default='PETROL', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
